[build]
  publish = "public"                    # Eleventy output folder
  command = "npm run endprod"        # Your build command

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"